# automatically generated by the FlatBuffers compiler, do not modify

# namespace: openmeteo_sdk

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from openmeteo_sdk.SeriesAndTime import SeriesAndTime
from openmeteo_sdk.SingleValueAndTime import SingleValueAndTime
from typing import Optional
np = import_numpy()

class ApiResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ApiResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsApiResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ApiResponse
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ApiResponse
    def Latitude(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ApiResponse
    def Longitude(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ApiResponse
    def Elevation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ApiResponse
    def LocationId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ApiResponse
    def Model(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # ApiResponse
    def GenerationtimeMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ApiResponse
    def UtcOffsetSeconds(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ApiResponse
    def Timezone(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ApiResponse
    def TimezoneAbbreviation(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ApiResponse
    def Current(self) -> Optional[SingleValueAndTime]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = SingleValueAndTime()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ApiResponse
    def Daily(self) -> Optional[SeriesAndTime]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = SeriesAndTime()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ApiResponse
    def Hourly(self) -> Optional[SeriesAndTime]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = SeriesAndTime()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ApiResponse
    def SixHourly(self) -> Optional[SeriesAndTime]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = SeriesAndTime()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ApiResponse
    def Minutely15(self) -> Optional[SeriesAndTime]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = SeriesAndTime()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def ApiResponseStart(builder: flatbuffers.Builder):
    builder.StartObject(14)

def Start(builder: flatbuffers.Builder):
    ApiResponseStart(builder)

def ApiResponseAddLatitude(builder: flatbuffers.Builder, latitude: float):
    builder.PrependFloat32Slot(0, latitude, 0.0)

def AddLatitude(builder: flatbuffers.Builder, latitude: float):
    ApiResponseAddLatitude(builder, latitude)

def ApiResponseAddLongitude(builder: flatbuffers.Builder, longitude: float):
    builder.PrependFloat32Slot(1, longitude, 0.0)

def AddLongitude(builder: flatbuffers.Builder, longitude: float):
    ApiResponseAddLongitude(builder, longitude)

def ApiResponseAddElevation(builder: flatbuffers.Builder, elevation: float):
    builder.PrependFloat32Slot(2, elevation, 0.0)

def AddElevation(builder: flatbuffers.Builder, elevation: float):
    ApiResponseAddElevation(builder, elevation)

def ApiResponseAddLocationId(builder: flatbuffers.Builder, locationId: int):
    builder.PrependInt32Slot(3, locationId, 0)

def AddLocationId(builder: flatbuffers.Builder, locationId: int):
    ApiResponseAddLocationId(builder, locationId)

def ApiResponseAddModel(builder: flatbuffers.Builder, model: int):
    builder.PrependInt8Slot(4, model, 0)

def AddModel(builder: flatbuffers.Builder, model: int):
    ApiResponseAddModel(builder, model)

def ApiResponseAddGenerationtimeMs(builder: flatbuffers.Builder, generationtimeMs: float):
    builder.PrependFloat32Slot(5, generationtimeMs, 0.0)

def AddGenerationtimeMs(builder: flatbuffers.Builder, generationtimeMs: float):
    ApiResponseAddGenerationtimeMs(builder, generationtimeMs)

def ApiResponseAddUtcOffsetSeconds(builder: flatbuffers.Builder, utcOffsetSeconds: int):
    builder.PrependInt32Slot(6, utcOffsetSeconds, 0)

def AddUtcOffsetSeconds(builder: flatbuffers.Builder, utcOffsetSeconds: int):
    ApiResponseAddUtcOffsetSeconds(builder, utcOffsetSeconds)

def ApiResponseAddTimezone(builder: flatbuffers.Builder, timezone: int):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(timezone), 0)

def AddTimezone(builder: flatbuffers.Builder, timezone: int):
    ApiResponseAddTimezone(builder, timezone)

def ApiResponseAddTimezoneAbbreviation(builder: flatbuffers.Builder, timezoneAbbreviation: int):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(timezoneAbbreviation), 0)

def AddTimezoneAbbreviation(builder: flatbuffers.Builder, timezoneAbbreviation: int):
    ApiResponseAddTimezoneAbbreviation(builder, timezoneAbbreviation)

def ApiResponseAddCurrent(builder: flatbuffers.Builder, current: int):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(current), 0)

def AddCurrent(builder: flatbuffers.Builder, current: int):
    ApiResponseAddCurrent(builder, current)

def ApiResponseAddDaily(builder: flatbuffers.Builder, daily: int):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(daily), 0)

def AddDaily(builder: flatbuffers.Builder, daily: int):
    ApiResponseAddDaily(builder, daily)

def ApiResponseAddHourly(builder: flatbuffers.Builder, hourly: int):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(hourly), 0)

def AddHourly(builder: flatbuffers.Builder, hourly: int):
    ApiResponseAddHourly(builder, hourly)

def ApiResponseAddSixHourly(builder: flatbuffers.Builder, sixHourly: int):
    builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(sixHourly), 0)

def AddSixHourly(builder: flatbuffers.Builder, sixHourly: int):
    ApiResponseAddSixHourly(builder, sixHourly)

def ApiResponseAddMinutely15(builder: flatbuffers.Builder, minutely15: int):
    builder.PrependUOffsetTRelativeSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(minutely15), 0)

def AddMinutely15(builder: flatbuffers.Builder, minutely15: int):
    ApiResponseAddMinutely15(builder, minutely15)

def ApiResponseEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return ApiResponseEnd(builder)
