# automatically generated by the FlatBuffers compiler, do not modify

# namespace: openmeteo_sdk

class ClimateModel(object):
    best_match = 0
    CMCC_CM2_VHR4 = 1
    FGOALS_f3_H_highresSST = 2
    FGOALS_f3_H = 3
    HiRAM_SIT_HR = 4
    MRI_AGCM3_2_S = 5
    EC_Earth3P_HR = 6
    MPI_ESM1_2_XR = 7
    NICAM16_8S = 8
