# automatically generated by the FlatBuffers compiler, do not modify

# namespace: openmeteo_sdk

class Probability(object):
    none = 0
    gt0 = 1
    gt0p1 = 2
    gt1 = 3
    gt2 = 4
    gt3 = 5
    gt4 = 6
    gt5 = 7
    gt8 = 8
    gt10 = 9
    gt15 = 10
    gt20 = 11
    gt25 = 12
    gt50 = 13
    gt100 = 14
    lt0 = 15
    lt0p1 = 16
    lt1 = 17
    ltm1 = 18
    ltm2 = 19
    ltm3 = 20
    ltm4 = 21
    ltm5 = 22
    ltm8 = 23
    ltm10 = 24
    gt1stdev = 25
    gt1p5stdev = 26
    gt2stdev = 27
    lt1stdev = 28
    lt1p5stdev = 29
    lt2stdev = 30
