# automatically generated by the FlatBuffers compiler, do not modify

# namespace: openmeteo_sdk

class Probability(object):
    none = 0
    gt0 = 1
    gt0p1 = 2
    gt1 = 3
    gt2 = 4
    gt3 = 5
    gt4 = 6
    gt5 = 7
    gt8 = 8
    gt10 = 9
    gt15 = 10
    gt20 = 11
    gt25 = 12
    gt30 = 13
    gt35 = 14
    gt40 = 15
    gt50 = 16
    gt60 = 17
    gt75 = 18
    gt80 = 19
    gt100 = 20
    lt0 = 21
    lt0p1 = 22
    lt1 = 23
    ltm1 = 24
    ltm2 = 25
    ltm3 = 26
    ltm4 = 27
    ltm5 = 28
    ltm8 = 29
    ltm10 = 30
    ltm15 = 31
    ltm20 = 32
    gt1stdev = 33
    gt1p5stdev = 34
    gt2stdev = 35
    lt1stdev = 36
    lt1p5stdev = 37
    lt2stdev = 38
