# automatically generated by the FlatBuffers compiler, do not modify

# namespace: openmeteo_sdk

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from openmeteo_sdk.Series import Series
from typing import Optional
np = import_numpy()

class SeriesAndTime(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SeriesAndTime()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSeriesAndTime(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SeriesAndTime
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SeriesAndTime
    def Start(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # SeriesAndTime
    def End(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # SeriesAndTime
    def Interval(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SeriesAndTime
    def Series(self, j: int) -> Optional[Series]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Series()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SeriesAndTime
    def SeriesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SeriesAndTime
    def SeriesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def SeriesAndTimeStart(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    SeriesAndTimeStart(builder)

def SeriesAndTimeAddStart(builder: flatbuffers.Builder, start: int):
    builder.PrependInt64Slot(0, start, 0)

def AddStart(builder: flatbuffers.Builder, start: int):
    SeriesAndTimeAddStart(builder, start)

def SeriesAndTimeAddEnd(builder: flatbuffers.Builder, end: int):
    builder.PrependInt64Slot(1, end, 0)

def AddEnd(builder: flatbuffers.Builder, end: int):
    SeriesAndTimeAddEnd(builder, end)

def SeriesAndTimeAddInterval(builder: flatbuffers.Builder, interval: int):
    builder.PrependInt32Slot(2, interval, 0)

def AddInterval(builder: flatbuffers.Builder, interval: int):
    SeriesAndTimeAddInterval(builder, interval)

def SeriesAndTimeAddSeries(builder: flatbuffers.Builder, series: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(series), 0)

def AddSeries(builder: flatbuffers.Builder, series: int):
    SeriesAndTimeAddSeries(builder, series)

def SeriesAndTimeStartSeriesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartSeriesVector(builder, numElems: int) -> int:
    return SeriesAndTimeStartSeriesVector(builder, numElems)

def SeriesAndTimeEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return SeriesAndTimeEnd(builder)
