// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { ValueAndUnit } from '../openmeteo-sdk/value-and-unit.js';


export class AirQualityCurrent {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):AirQualityCurrent {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAirQualityCurrent(bb:flatbuffers.ByteBuffer, obj?:AirQualityCurrent):AirQualityCurrent {
  return (obj || new AirQualityCurrent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAirQualityCurrent(bb:flatbuffers.ByteBuffer, obj?:AirQualityCurrent):AirQualityCurrent {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new AirQualityCurrent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

time():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

interval():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

pm10(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

pm25(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

dust(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

aerosolOpticalDepth(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

carbonMonoxide(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

nitrogenDioxide(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

ammonia(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

ozone(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

sulphurDioxide(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

uvIndex(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

uvIndexClearSky(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

alderPollen(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

birchPollen(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 32);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

grassPollen(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 34);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

mugwortPollen(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 36);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

olivePollen(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 38);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

ragweedPollen(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 40);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

europeanAqi(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 42);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

europeanAqiPm25(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 44);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

europeanAqiPm10(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 46);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

europeanAqiNo2(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 48);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

europeanAqiO3(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 50);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

europeanAqiSo2(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 52);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

usAqi(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 54);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

usAqiPm25(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 56);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

usAqiPm10(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 58);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

usAqiNo2(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 60);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

usAqiO3(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 62);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

usAqiSo2(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 64);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

usAqiCo(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 66);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

isDay(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 68);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

static startAirQualityCurrent(builder:flatbuffers.Builder) {
  builder.startObject(33);
}

static addTime(builder:flatbuffers.Builder, time:bigint) {
  builder.addFieldInt64(0, time, BigInt('0'));
}

static addInterval(builder:flatbuffers.Builder, interval:number) {
  builder.addFieldInt32(1, interval, 0);
}

static addPm10(builder:flatbuffers.Builder, pm10Offset:flatbuffers.Offset) {
  builder.addFieldStruct(2, pm10Offset, 0);
}

static addPm25(builder:flatbuffers.Builder, pm25Offset:flatbuffers.Offset) {
  builder.addFieldStruct(3, pm25Offset, 0);
}

static addDust(builder:flatbuffers.Builder, dustOffset:flatbuffers.Offset) {
  builder.addFieldStruct(4, dustOffset, 0);
}

static addAerosolOpticalDepth(builder:flatbuffers.Builder, aerosolOpticalDepthOffset:flatbuffers.Offset) {
  builder.addFieldStruct(5, aerosolOpticalDepthOffset, 0);
}

static addCarbonMonoxide(builder:flatbuffers.Builder, carbonMonoxideOffset:flatbuffers.Offset) {
  builder.addFieldStruct(6, carbonMonoxideOffset, 0);
}

static addNitrogenDioxide(builder:flatbuffers.Builder, nitrogenDioxideOffset:flatbuffers.Offset) {
  builder.addFieldStruct(7, nitrogenDioxideOffset, 0);
}

static addAmmonia(builder:flatbuffers.Builder, ammoniaOffset:flatbuffers.Offset) {
  builder.addFieldStruct(8, ammoniaOffset, 0);
}

static addOzone(builder:flatbuffers.Builder, ozoneOffset:flatbuffers.Offset) {
  builder.addFieldStruct(9, ozoneOffset, 0);
}

static addSulphurDioxide(builder:flatbuffers.Builder, sulphurDioxideOffset:flatbuffers.Offset) {
  builder.addFieldStruct(10, sulphurDioxideOffset, 0);
}

static addUvIndex(builder:flatbuffers.Builder, uvIndexOffset:flatbuffers.Offset) {
  builder.addFieldStruct(11, uvIndexOffset, 0);
}

static addUvIndexClearSky(builder:flatbuffers.Builder, uvIndexClearSkyOffset:flatbuffers.Offset) {
  builder.addFieldStruct(12, uvIndexClearSkyOffset, 0);
}

static addAlderPollen(builder:flatbuffers.Builder, alderPollenOffset:flatbuffers.Offset) {
  builder.addFieldStruct(13, alderPollenOffset, 0);
}

static addBirchPollen(builder:flatbuffers.Builder, birchPollenOffset:flatbuffers.Offset) {
  builder.addFieldStruct(14, birchPollenOffset, 0);
}

static addGrassPollen(builder:flatbuffers.Builder, grassPollenOffset:flatbuffers.Offset) {
  builder.addFieldStruct(15, grassPollenOffset, 0);
}

static addMugwortPollen(builder:flatbuffers.Builder, mugwortPollenOffset:flatbuffers.Offset) {
  builder.addFieldStruct(16, mugwortPollenOffset, 0);
}

static addOlivePollen(builder:flatbuffers.Builder, olivePollenOffset:flatbuffers.Offset) {
  builder.addFieldStruct(17, olivePollenOffset, 0);
}

static addRagweedPollen(builder:flatbuffers.Builder, ragweedPollenOffset:flatbuffers.Offset) {
  builder.addFieldStruct(18, ragweedPollenOffset, 0);
}

static addEuropeanAqi(builder:flatbuffers.Builder, europeanAqiOffset:flatbuffers.Offset) {
  builder.addFieldStruct(19, europeanAqiOffset, 0);
}

static addEuropeanAqiPm25(builder:flatbuffers.Builder, europeanAqiPm25Offset:flatbuffers.Offset) {
  builder.addFieldStruct(20, europeanAqiPm25Offset, 0);
}

static addEuropeanAqiPm10(builder:flatbuffers.Builder, europeanAqiPm10Offset:flatbuffers.Offset) {
  builder.addFieldStruct(21, europeanAqiPm10Offset, 0);
}

static addEuropeanAqiNo2(builder:flatbuffers.Builder, europeanAqiNo2Offset:flatbuffers.Offset) {
  builder.addFieldStruct(22, europeanAqiNo2Offset, 0);
}

static addEuropeanAqiO3(builder:flatbuffers.Builder, europeanAqiO3Offset:flatbuffers.Offset) {
  builder.addFieldStruct(23, europeanAqiO3Offset, 0);
}

static addEuropeanAqiSo2(builder:flatbuffers.Builder, europeanAqiSo2Offset:flatbuffers.Offset) {
  builder.addFieldStruct(24, europeanAqiSo2Offset, 0);
}

static addUsAqi(builder:flatbuffers.Builder, usAqiOffset:flatbuffers.Offset) {
  builder.addFieldStruct(25, usAqiOffset, 0);
}

static addUsAqiPm25(builder:flatbuffers.Builder, usAqiPm25Offset:flatbuffers.Offset) {
  builder.addFieldStruct(26, usAqiPm25Offset, 0);
}

static addUsAqiPm10(builder:flatbuffers.Builder, usAqiPm10Offset:flatbuffers.Offset) {
  builder.addFieldStruct(27, usAqiPm10Offset, 0);
}

static addUsAqiNo2(builder:flatbuffers.Builder, usAqiNo2Offset:flatbuffers.Offset) {
  builder.addFieldStruct(28, usAqiNo2Offset, 0);
}

static addUsAqiO3(builder:flatbuffers.Builder, usAqiO3Offset:flatbuffers.Offset) {
  builder.addFieldStruct(29, usAqiO3Offset, 0);
}

static addUsAqiSo2(builder:flatbuffers.Builder, usAqiSo2Offset:flatbuffers.Offset) {
  builder.addFieldStruct(30, usAqiSo2Offset, 0);
}

static addUsAqiCo(builder:flatbuffers.Builder, usAqiCoOffset:flatbuffers.Offset) {
  builder.addFieldStruct(31, usAqiCoOffset, 0);
}

static addIsDay(builder:flatbuffers.Builder, isDayOffset:flatbuffers.Offset) {
  builder.addFieldStruct(32, isDayOffset, 0);
}

static endAirQualityCurrent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
