// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { Series } from './series.js';


export class SeriesAndTime {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SeriesAndTime {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSeriesAndTime(bb:flatbuffers.ByteBuffer, obj?:SeriesAndTime):SeriesAndTime {
  return (obj || new SeriesAndTime()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSeriesAndTime(bb:flatbuffers.ByteBuffer, obj?:SeriesAndTime):SeriesAndTime {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SeriesAndTime()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

start():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

end():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

interval():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

series(index: number, obj?:Series):Series|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Series()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

seriesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startSeriesAndTime(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addStart(builder:flatbuffers.Builder, start:bigint) {
  builder.addFieldInt64(0, start, BigInt('0'));
}

static addEnd(builder:flatbuffers.Builder, end:bigint) {
  builder.addFieldInt64(1, end, BigInt('0'));
}

static addInterval(builder:flatbuffers.Builder, interval:number) {
  builder.addFieldInt32(2, interval, 0);
}

static addSeries(builder:flatbuffers.Builder, seriesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, seriesOffset, 0);
}

static createSeriesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startSeriesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endSeriesAndTime(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSeriesAndTime(builder:flatbuffers.Builder, start:bigint, end:bigint, interval:number, seriesOffset:flatbuffers.Offset):flatbuffers.Offset {
  SeriesAndTime.startSeriesAndTime(builder);
  SeriesAndTime.addStart(builder, start);
  SeriesAndTime.addEnd(builder, end);
  SeriesAndTime.addInterval(builder, interval);
  SeriesAndTime.addSeries(builder, seriesOffset);
  return SeriesAndTime.endSeriesAndTime(builder);
}
}
