// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { ValueAndUnit } from './value-and-unit.js';


export class WeatherCurrent {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):WeatherCurrent {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsWeatherCurrent(bb:flatbuffers.ByteBuffer, obj?:WeatherCurrent):WeatherCurrent {
  return (obj || new WeatherCurrent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsWeatherCurrent(bb:flatbuffers.ByteBuffer, obj?:WeatherCurrent):WeatherCurrent {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new WeatherCurrent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

time():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

interval():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

apparentTemperature(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

cape(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

cloudcover(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

cloudcoverHigh(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

cloudcoverLow(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

cloudcoverMid(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

dewpoint2m(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

diffuseRadiation(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

diffuseRadiationInstant(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

directNormalIrradiance(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

directNormalIrradianceInstant(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

directRadiation(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

directRadiationInstant(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 32);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

et0FaoEvapotranspiration(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 34);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

evapotranspiration(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 36);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

freezinglevelHeight(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 38);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

growingDegreeDaysBase0Limit50(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 40);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

isDay(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 42);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

latentHeatflux(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 44);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

leafWetnessProbability(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 46);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

liftedIndex(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 48);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

lightningPotential(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 50);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

precipitation(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 52);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

precipitationProbability(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 54);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

pressureMsl(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 56);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

rain(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 58);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

relativehumidity2m(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 60);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

runoff(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 62);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

sensibleHeatflux(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 64);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

shortwaveRadiation(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 66);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

shortwaveRadiationInstant(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 68);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

showers(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 70);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

snowDepth(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 72);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

snowHeight(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 74);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

snowfall(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 76);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

snowfallHeight(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 78);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

snowfallWaterEquivalent(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 80);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

soilMoisture0To1cm(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 82);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

soilMoisture0To100cm(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 84);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

soilMoisture0To10cm(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 86);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

soilMoisture0To7cm(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 88);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

soilMoisture100To200cm(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 90);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

soilMoisture100To255cm(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 92);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

soilMoisture10To40cm(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 94);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

soilMoisture1To3cm(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 96);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

soilMoisture27To81cm(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 98);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

soilMoisture28To100cm(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 100);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

soilMoisture3To9cm(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 102);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

soilMoisture40To100cm(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 104);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

soilMoisture7To28cm(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 106);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

soilMoisture9To27cm(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 108);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

soilMoistureIndex0To100cm(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 110);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

soilMoistureIndex0To7cm(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 112);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

soilMoistureIndex100To255cm(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 114);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

soilMoistureIndex28To100cm(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 116);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

soilMoistureIndex7To28cm(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 118);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

soilTemperature0To100cm(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 120);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

soilTemperature0To10cm(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 122);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

soilTemperature0To7cm(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 124);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

soilTemperature0cm(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 126);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

soilTemperature100To200cm(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 128);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

soilTemperature100To255cm(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 130);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

soilTemperature10To40cm(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 132);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

soilTemperature18cm(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 134);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

soilTemperature28To100cm(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 136);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

soilTemperature40To100cm(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 138);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

soilTemperature54cm(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 140);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

soilTemperature6cm(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 142);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

soilTemperature7To28cm(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 144);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

surfacePressure(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 146);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

surfaceTemperature(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 148);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

temperature100m(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 150);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

temperature120m(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 152);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

temperature150m(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 154);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

temperature180m(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 156);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

temperature2m(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 158);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

temperature20m(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 160);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

temperature200m(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 162);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

temperature50m(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 164);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

temperature40m(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 166);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

temperature80m(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 168);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

terrestrialRadiation(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 170);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

terrestrialRadiationInstant(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 172);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

totalColumnIntegratedWaterVapour(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 174);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

updraft(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 176);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

uvIndex(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 178);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

uvIndexClearSky(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 180);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

vaporPressureDeficit(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 182);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

visibility(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 184);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

weathercode(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 186);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

winddirection100m(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 188);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

winddirection10m(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 190);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

winddirection120m(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 192);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

winddirection150m(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 194);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

winddirection180m(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 196);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

winddirection200m(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 198);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

winddirection20m(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 200);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

winddirection40m(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 202);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

winddirection50m(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 204);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

winddirection80m(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 206);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

windgusts10m(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 208);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

windspeed100m(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 210);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

windspeed10m(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 212);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

windspeed120m(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 214);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

windspeed150m(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 216);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

windspeed180m(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 218);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

windspeed200m(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 220);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

windspeed20m(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 222);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

windspeed40m(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 224);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

windspeed50m(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 226);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

windspeed80m(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 228);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

wetBulbTemperature2m(obj?:ValueAndUnit):ValueAndUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 230);
  return offset ? (obj || new ValueAndUnit()).__init(this.bb_pos + offset, this.bb!) : null;
}

static startWeatherCurrent(builder:flatbuffers.Builder) {
  builder.startObject(114);
}

static addTime(builder:flatbuffers.Builder, time:bigint) {
  builder.addFieldInt64(0, time, BigInt('0'));
}

static addInterval(builder:flatbuffers.Builder, interval:number) {
  builder.addFieldInt32(1, interval, 0);
}

static addApparentTemperature(builder:flatbuffers.Builder, apparentTemperatureOffset:flatbuffers.Offset) {
  builder.addFieldStruct(2, apparentTemperatureOffset, 0);
}

static addCape(builder:flatbuffers.Builder, capeOffset:flatbuffers.Offset) {
  builder.addFieldStruct(3, capeOffset, 0);
}

static addCloudcover(builder:flatbuffers.Builder, cloudcoverOffset:flatbuffers.Offset) {
  builder.addFieldStruct(4, cloudcoverOffset, 0);
}

static addCloudcoverHigh(builder:flatbuffers.Builder, cloudcoverHighOffset:flatbuffers.Offset) {
  builder.addFieldStruct(5, cloudcoverHighOffset, 0);
}

static addCloudcoverLow(builder:flatbuffers.Builder, cloudcoverLowOffset:flatbuffers.Offset) {
  builder.addFieldStruct(6, cloudcoverLowOffset, 0);
}

static addCloudcoverMid(builder:flatbuffers.Builder, cloudcoverMidOffset:flatbuffers.Offset) {
  builder.addFieldStruct(7, cloudcoverMidOffset, 0);
}

static addDewpoint2m(builder:flatbuffers.Builder, dewpoint2mOffset:flatbuffers.Offset) {
  builder.addFieldStruct(8, dewpoint2mOffset, 0);
}

static addDiffuseRadiation(builder:flatbuffers.Builder, diffuseRadiationOffset:flatbuffers.Offset) {
  builder.addFieldStruct(9, diffuseRadiationOffset, 0);
}

static addDiffuseRadiationInstant(builder:flatbuffers.Builder, diffuseRadiationInstantOffset:flatbuffers.Offset) {
  builder.addFieldStruct(10, diffuseRadiationInstantOffset, 0);
}

static addDirectNormalIrradiance(builder:flatbuffers.Builder, directNormalIrradianceOffset:flatbuffers.Offset) {
  builder.addFieldStruct(11, directNormalIrradianceOffset, 0);
}

static addDirectNormalIrradianceInstant(builder:flatbuffers.Builder, directNormalIrradianceInstantOffset:flatbuffers.Offset) {
  builder.addFieldStruct(12, directNormalIrradianceInstantOffset, 0);
}

static addDirectRadiation(builder:flatbuffers.Builder, directRadiationOffset:flatbuffers.Offset) {
  builder.addFieldStruct(13, directRadiationOffset, 0);
}

static addDirectRadiationInstant(builder:flatbuffers.Builder, directRadiationInstantOffset:flatbuffers.Offset) {
  builder.addFieldStruct(14, directRadiationInstantOffset, 0);
}

static addEt0FaoEvapotranspiration(builder:flatbuffers.Builder, et0FaoEvapotranspirationOffset:flatbuffers.Offset) {
  builder.addFieldStruct(15, et0FaoEvapotranspirationOffset, 0);
}

static addEvapotranspiration(builder:flatbuffers.Builder, evapotranspirationOffset:flatbuffers.Offset) {
  builder.addFieldStruct(16, evapotranspirationOffset, 0);
}

static addFreezinglevelHeight(builder:flatbuffers.Builder, freezinglevelHeightOffset:flatbuffers.Offset) {
  builder.addFieldStruct(17, freezinglevelHeightOffset, 0);
}

static addGrowingDegreeDaysBase0Limit50(builder:flatbuffers.Builder, growingDegreeDaysBase0Limit50Offset:flatbuffers.Offset) {
  builder.addFieldStruct(18, growingDegreeDaysBase0Limit50Offset, 0);
}

static addIsDay(builder:flatbuffers.Builder, isDayOffset:flatbuffers.Offset) {
  builder.addFieldStruct(19, isDayOffset, 0);
}

static addLatentHeatflux(builder:flatbuffers.Builder, latentHeatfluxOffset:flatbuffers.Offset) {
  builder.addFieldStruct(20, latentHeatfluxOffset, 0);
}

static addLeafWetnessProbability(builder:flatbuffers.Builder, leafWetnessProbabilityOffset:flatbuffers.Offset) {
  builder.addFieldStruct(21, leafWetnessProbabilityOffset, 0);
}

static addLiftedIndex(builder:flatbuffers.Builder, liftedIndexOffset:flatbuffers.Offset) {
  builder.addFieldStruct(22, liftedIndexOffset, 0);
}

static addLightningPotential(builder:flatbuffers.Builder, lightningPotentialOffset:flatbuffers.Offset) {
  builder.addFieldStruct(23, lightningPotentialOffset, 0);
}

static addPrecipitation(builder:flatbuffers.Builder, precipitationOffset:flatbuffers.Offset) {
  builder.addFieldStruct(24, precipitationOffset, 0);
}

static addPrecipitationProbability(builder:flatbuffers.Builder, precipitationProbabilityOffset:flatbuffers.Offset) {
  builder.addFieldStruct(25, precipitationProbabilityOffset, 0);
}

static addPressureMsl(builder:flatbuffers.Builder, pressureMslOffset:flatbuffers.Offset) {
  builder.addFieldStruct(26, pressureMslOffset, 0);
}

static addRain(builder:flatbuffers.Builder, rainOffset:flatbuffers.Offset) {
  builder.addFieldStruct(27, rainOffset, 0);
}

static addRelativehumidity2m(builder:flatbuffers.Builder, relativehumidity2mOffset:flatbuffers.Offset) {
  builder.addFieldStruct(28, relativehumidity2mOffset, 0);
}

static addRunoff(builder:flatbuffers.Builder, runoffOffset:flatbuffers.Offset) {
  builder.addFieldStruct(29, runoffOffset, 0);
}

static addSensibleHeatflux(builder:flatbuffers.Builder, sensibleHeatfluxOffset:flatbuffers.Offset) {
  builder.addFieldStruct(30, sensibleHeatfluxOffset, 0);
}

static addShortwaveRadiation(builder:flatbuffers.Builder, shortwaveRadiationOffset:flatbuffers.Offset) {
  builder.addFieldStruct(31, shortwaveRadiationOffset, 0);
}

static addShortwaveRadiationInstant(builder:flatbuffers.Builder, shortwaveRadiationInstantOffset:flatbuffers.Offset) {
  builder.addFieldStruct(32, shortwaveRadiationInstantOffset, 0);
}

static addShowers(builder:flatbuffers.Builder, showersOffset:flatbuffers.Offset) {
  builder.addFieldStruct(33, showersOffset, 0);
}

static addSnowDepth(builder:flatbuffers.Builder, snowDepthOffset:flatbuffers.Offset) {
  builder.addFieldStruct(34, snowDepthOffset, 0);
}

static addSnowHeight(builder:flatbuffers.Builder, snowHeightOffset:flatbuffers.Offset) {
  builder.addFieldStruct(35, snowHeightOffset, 0);
}

static addSnowfall(builder:flatbuffers.Builder, snowfallOffset:flatbuffers.Offset) {
  builder.addFieldStruct(36, snowfallOffset, 0);
}

static addSnowfallHeight(builder:flatbuffers.Builder, snowfallHeightOffset:flatbuffers.Offset) {
  builder.addFieldStruct(37, snowfallHeightOffset, 0);
}

static addSnowfallWaterEquivalent(builder:flatbuffers.Builder, snowfallWaterEquivalentOffset:flatbuffers.Offset) {
  builder.addFieldStruct(38, snowfallWaterEquivalentOffset, 0);
}

static addSoilMoisture0To1cm(builder:flatbuffers.Builder, soilMoisture0To1cmOffset:flatbuffers.Offset) {
  builder.addFieldStruct(39, soilMoisture0To1cmOffset, 0);
}

static addSoilMoisture0To100cm(builder:flatbuffers.Builder, soilMoisture0To100cmOffset:flatbuffers.Offset) {
  builder.addFieldStruct(40, soilMoisture0To100cmOffset, 0);
}

static addSoilMoisture0To10cm(builder:flatbuffers.Builder, soilMoisture0To10cmOffset:flatbuffers.Offset) {
  builder.addFieldStruct(41, soilMoisture0To10cmOffset, 0);
}

static addSoilMoisture0To7cm(builder:flatbuffers.Builder, soilMoisture0To7cmOffset:flatbuffers.Offset) {
  builder.addFieldStruct(42, soilMoisture0To7cmOffset, 0);
}

static addSoilMoisture100To200cm(builder:flatbuffers.Builder, soilMoisture100To200cmOffset:flatbuffers.Offset) {
  builder.addFieldStruct(43, soilMoisture100To200cmOffset, 0);
}

static addSoilMoisture100To255cm(builder:flatbuffers.Builder, soilMoisture100To255cmOffset:flatbuffers.Offset) {
  builder.addFieldStruct(44, soilMoisture100To255cmOffset, 0);
}

static addSoilMoisture10To40cm(builder:flatbuffers.Builder, soilMoisture10To40cmOffset:flatbuffers.Offset) {
  builder.addFieldStruct(45, soilMoisture10To40cmOffset, 0);
}

static addSoilMoisture1To3cm(builder:flatbuffers.Builder, soilMoisture1To3cmOffset:flatbuffers.Offset) {
  builder.addFieldStruct(46, soilMoisture1To3cmOffset, 0);
}

static addSoilMoisture27To81cm(builder:flatbuffers.Builder, soilMoisture27To81cmOffset:flatbuffers.Offset) {
  builder.addFieldStruct(47, soilMoisture27To81cmOffset, 0);
}

static addSoilMoisture28To100cm(builder:flatbuffers.Builder, soilMoisture28To100cmOffset:flatbuffers.Offset) {
  builder.addFieldStruct(48, soilMoisture28To100cmOffset, 0);
}

static addSoilMoisture3To9cm(builder:flatbuffers.Builder, soilMoisture3To9cmOffset:flatbuffers.Offset) {
  builder.addFieldStruct(49, soilMoisture3To9cmOffset, 0);
}

static addSoilMoisture40To100cm(builder:flatbuffers.Builder, soilMoisture40To100cmOffset:flatbuffers.Offset) {
  builder.addFieldStruct(50, soilMoisture40To100cmOffset, 0);
}

static addSoilMoisture7To28cm(builder:flatbuffers.Builder, soilMoisture7To28cmOffset:flatbuffers.Offset) {
  builder.addFieldStruct(51, soilMoisture7To28cmOffset, 0);
}

static addSoilMoisture9To27cm(builder:flatbuffers.Builder, soilMoisture9To27cmOffset:flatbuffers.Offset) {
  builder.addFieldStruct(52, soilMoisture9To27cmOffset, 0);
}

static addSoilMoistureIndex0To100cm(builder:flatbuffers.Builder, soilMoistureIndex0To100cmOffset:flatbuffers.Offset) {
  builder.addFieldStruct(53, soilMoistureIndex0To100cmOffset, 0);
}

static addSoilMoistureIndex0To7cm(builder:flatbuffers.Builder, soilMoistureIndex0To7cmOffset:flatbuffers.Offset) {
  builder.addFieldStruct(54, soilMoistureIndex0To7cmOffset, 0);
}

static addSoilMoistureIndex100To255cm(builder:flatbuffers.Builder, soilMoistureIndex100To255cmOffset:flatbuffers.Offset) {
  builder.addFieldStruct(55, soilMoistureIndex100To255cmOffset, 0);
}

static addSoilMoistureIndex28To100cm(builder:flatbuffers.Builder, soilMoistureIndex28To100cmOffset:flatbuffers.Offset) {
  builder.addFieldStruct(56, soilMoistureIndex28To100cmOffset, 0);
}

static addSoilMoistureIndex7To28cm(builder:flatbuffers.Builder, soilMoistureIndex7To28cmOffset:flatbuffers.Offset) {
  builder.addFieldStruct(57, soilMoistureIndex7To28cmOffset, 0);
}

static addSoilTemperature0To100cm(builder:flatbuffers.Builder, soilTemperature0To100cmOffset:flatbuffers.Offset) {
  builder.addFieldStruct(58, soilTemperature0To100cmOffset, 0);
}

static addSoilTemperature0To10cm(builder:flatbuffers.Builder, soilTemperature0To10cmOffset:flatbuffers.Offset) {
  builder.addFieldStruct(59, soilTemperature0To10cmOffset, 0);
}

static addSoilTemperature0To7cm(builder:flatbuffers.Builder, soilTemperature0To7cmOffset:flatbuffers.Offset) {
  builder.addFieldStruct(60, soilTemperature0To7cmOffset, 0);
}

static addSoilTemperature0cm(builder:flatbuffers.Builder, soilTemperature0cmOffset:flatbuffers.Offset) {
  builder.addFieldStruct(61, soilTemperature0cmOffset, 0);
}

static addSoilTemperature100To200cm(builder:flatbuffers.Builder, soilTemperature100To200cmOffset:flatbuffers.Offset) {
  builder.addFieldStruct(62, soilTemperature100To200cmOffset, 0);
}

static addSoilTemperature100To255cm(builder:flatbuffers.Builder, soilTemperature100To255cmOffset:flatbuffers.Offset) {
  builder.addFieldStruct(63, soilTemperature100To255cmOffset, 0);
}

static addSoilTemperature10To40cm(builder:flatbuffers.Builder, soilTemperature10To40cmOffset:flatbuffers.Offset) {
  builder.addFieldStruct(64, soilTemperature10To40cmOffset, 0);
}

static addSoilTemperature18cm(builder:flatbuffers.Builder, soilTemperature18cmOffset:flatbuffers.Offset) {
  builder.addFieldStruct(65, soilTemperature18cmOffset, 0);
}

static addSoilTemperature28To100cm(builder:flatbuffers.Builder, soilTemperature28To100cmOffset:flatbuffers.Offset) {
  builder.addFieldStruct(66, soilTemperature28To100cmOffset, 0);
}

static addSoilTemperature40To100cm(builder:flatbuffers.Builder, soilTemperature40To100cmOffset:flatbuffers.Offset) {
  builder.addFieldStruct(67, soilTemperature40To100cmOffset, 0);
}

static addSoilTemperature54cm(builder:flatbuffers.Builder, soilTemperature54cmOffset:flatbuffers.Offset) {
  builder.addFieldStruct(68, soilTemperature54cmOffset, 0);
}

static addSoilTemperature6cm(builder:flatbuffers.Builder, soilTemperature6cmOffset:flatbuffers.Offset) {
  builder.addFieldStruct(69, soilTemperature6cmOffset, 0);
}

static addSoilTemperature7To28cm(builder:flatbuffers.Builder, soilTemperature7To28cmOffset:flatbuffers.Offset) {
  builder.addFieldStruct(70, soilTemperature7To28cmOffset, 0);
}

static addSurfacePressure(builder:flatbuffers.Builder, surfacePressureOffset:flatbuffers.Offset) {
  builder.addFieldStruct(71, surfacePressureOffset, 0);
}

static addSurfaceTemperature(builder:flatbuffers.Builder, surfaceTemperatureOffset:flatbuffers.Offset) {
  builder.addFieldStruct(72, surfaceTemperatureOffset, 0);
}

static addTemperature100m(builder:flatbuffers.Builder, temperature100mOffset:flatbuffers.Offset) {
  builder.addFieldStruct(73, temperature100mOffset, 0);
}

static addTemperature120m(builder:flatbuffers.Builder, temperature120mOffset:flatbuffers.Offset) {
  builder.addFieldStruct(74, temperature120mOffset, 0);
}

static addTemperature150m(builder:flatbuffers.Builder, temperature150mOffset:flatbuffers.Offset) {
  builder.addFieldStruct(75, temperature150mOffset, 0);
}

static addTemperature180m(builder:flatbuffers.Builder, temperature180mOffset:flatbuffers.Offset) {
  builder.addFieldStruct(76, temperature180mOffset, 0);
}

static addTemperature2m(builder:flatbuffers.Builder, temperature2mOffset:flatbuffers.Offset) {
  builder.addFieldStruct(77, temperature2mOffset, 0);
}

static addTemperature20m(builder:flatbuffers.Builder, temperature20mOffset:flatbuffers.Offset) {
  builder.addFieldStruct(78, temperature20mOffset, 0);
}

static addTemperature200m(builder:flatbuffers.Builder, temperature200mOffset:flatbuffers.Offset) {
  builder.addFieldStruct(79, temperature200mOffset, 0);
}

static addTemperature50m(builder:flatbuffers.Builder, temperature50mOffset:flatbuffers.Offset) {
  builder.addFieldStruct(80, temperature50mOffset, 0);
}

static addTemperature40m(builder:flatbuffers.Builder, temperature40mOffset:flatbuffers.Offset) {
  builder.addFieldStruct(81, temperature40mOffset, 0);
}

static addTemperature80m(builder:flatbuffers.Builder, temperature80mOffset:flatbuffers.Offset) {
  builder.addFieldStruct(82, temperature80mOffset, 0);
}

static addTerrestrialRadiation(builder:flatbuffers.Builder, terrestrialRadiationOffset:flatbuffers.Offset) {
  builder.addFieldStruct(83, terrestrialRadiationOffset, 0);
}

static addTerrestrialRadiationInstant(builder:flatbuffers.Builder, terrestrialRadiationInstantOffset:flatbuffers.Offset) {
  builder.addFieldStruct(84, terrestrialRadiationInstantOffset, 0);
}

static addTotalColumnIntegratedWaterVapour(builder:flatbuffers.Builder, totalColumnIntegratedWaterVapourOffset:flatbuffers.Offset) {
  builder.addFieldStruct(85, totalColumnIntegratedWaterVapourOffset, 0);
}

static addUpdraft(builder:flatbuffers.Builder, updraftOffset:flatbuffers.Offset) {
  builder.addFieldStruct(86, updraftOffset, 0);
}

static addUvIndex(builder:flatbuffers.Builder, uvIndexOffset:flatbuffers.Offset) {
  builder.addFieldStruct(87, uvIndexOffset, 0);
}

static addUvIndexClearSky(builder:flatbuffers.Builder, uvIndexClearSkyOffset:flatbuffers.Offset) {
  builder.addFieldStruct(88, uvIndexClearSkyOffset, 0);
}

static addVaporPressureDeficit(builder:flatbuffers.Builder, vaporPressureDeficitOffset:flatbuffers.Offset) {
  builder.addFieldStruct(89, vaporPressureDeficitOffset, 0);
}

static addVisibility(builder:flatbuffers.Builder, visibilityOffset:flatbuffers.Offset) {
  builder.addFieldStruct(90, visibilityOffset, 0);
}

static addWeathercode(builder:flatbuffers.Builder, weathercodeOffset:flatbuffers.Offset) {
  builder.addFieldStruct(91, weathercodeOffset, 0);
}

static addWinddirection100m(builder:flatbuffers.Builder, winddirection100mOffset:flatbuffers.Offset) {
  builder.addFieldStruct(92, winddirection100mOffset, 0);
}

static addWinddirection10m(builder:flatbuffers.Builder, winddirection10mOffset:flatbuffers.Offset) {
  builder.addFieldStruct(93, winddirection10mOffset, 0);
}

static addWinddirection120m(builder:flatbuffers.Builder, winddirection120mOffset:flatbuffers.Offset) {
  builder.addFieldStruct(94, winddirection120mOffset, 0);
}

static addWinddirection150m(builder:flatbuffers.Builder, winddirection150mOffset:flatbuffers.Offset) {
  builder.addFieldStruct(95, winddirection150mOffset, 0);
}

static addWinddirection180m(builder:flatbuffers.Builder, winddirection180mOffset:flatbuffers.Offset) {
  builder.addFieldStruct(96, winddirection180mOffset, 0);
}

static addWinddirection200m(builder:flatbuffers.Builder, winddirection200mOffset:flatbuffers.Offset) {
  builder.addFieldStruct(97, winddirection200mOffset, 0);
}

static addWinddirection20m(builder:flatbuffers.Builder, winddirection20mOffset:flatbuffers.Offset) {
  builder.addFieldStruct(98, winddirection20mOffset, 0);
}

static addWinddirection40m(builder:flatbuffers.Builder, winddirection40mOffset:flatbuffers.Offset) {
  builder.addFieldStruct(99, winddirection40mOffset, 0);
}

static addWinddirection50m(builder:flatbuffers.Builder, winddirection50mOffset:flatbuffers.Offset) {
  builder.addFieldStruct(100, winddirection50mOffset, 0);
}

static addWinddirection80m(builder:flatbuffers.Builder, winddirection80mOffset:flatbuffers.Offset) {
  builder.addFieldStruct(101, winddirection80mOffset, 0);
}

static addWindgusts10m(builder:flatbuffers.Builder, windgusts10mOffset:flatbuffers.Offset) {
  builder.addFieldStruct(102, windgusts10mOffset, 0);
}

static addWindspeed100m(builder:flatbuffers.Builder, windspeed100mOffset:flatbuffers.Offset) {
  builder.addFieldStruct(103, windspeed100mOffset, 0);
}

static addWindspeed10m(builder:flatbuffers.Builder, windspeed10mOffset:flatbuffers.Offset) {
  builder.addFieldStruct(104, windspeed10mOffset, 0);
}

static addWindspeed120m(builder:flatbuffers.Builder, windspeed120mOffset:flatbuffers.Offset) {
  builder.addFieldStruct(105, windspeed120mOffset, 0);
}

static addWindspeed150m(builder:flatbuffers.Builder, windspeed150mOffset:flatbuffers.Offset) {
  builder.addFieldStruct(106, windspeed150mOffset, 0);
}

static addWindspeed180m(builder:flatbuffers.Builder, windspeed180mOffset:flatbuffers.Offset) {
  builder.addFieldStruct(107, windspeed180mOffset, 0);
}

static addWindspeed200m(builder:flatbuffers.Builder, windspeed200mOffset:flatbuffers.Offset) {
  builder.addFieldStruct(108, windspeed200mOffset, 0);
}

static addWindspeed20m(builder:flatbuffers.Builder, windspeed20mOffset:flatbuffers.Offset) {
  builder.addFieldStruct(109, windspeed20mOffset, 0);
}

static addWindspeed40m(builder:flatbuffers.Builder, windspeed40mOffset:flatbuffers.Offset) {
  builder.addFieldStruct(110, windspeed40mOffset, 0);
}

static addWindspeed50m(builder:flatbuffers.Builder, windspeed50mOffset:flatbuffers.Offset) {
  builder.addFieldStruct(111, windspeed50mOffset, 0);
}

static addWindspeed80m(builder:flatbuffers.Builder, windspeed80mOffset:flatbuffers.Offset) {
  builder.addFieldStruct(112, windspeed80mOffset, 0);
}

static addWetBulbTemperature2m(builder:flatbuffers.Builder, wetBulbTemperature2mOffset:flatbuffers.Offset) {
  builder.addFieldStruct(113, wetBulbTemperature2mOffset, 0);
}

static endWeatherCurrent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
