// automatically generated by the FlatBuffers compiler, do not modify

package com.openmeteo.sdk

@Suppress("unused")
class Probability private constructor() {
    companion object {
        const val none: UByte = 0u
        const val gt0: UByte = 1u
        const val gt0p1: UByte = 2u
        const val gt1: UByte = 3u
        const val gt2: UByte = 4u
        const val gt3: UByte = 5u
        const val gt4: UByte = 6u
        const val gt5: UByte = 7u
        const val gt8: UByte = 8u
        const val gt10: UByte = 9u
        const val gt15: UByte = 10u
        const val gt20: UByte = 11u
        const val gt25: UByte = 12u
        const val gt30: UByte = 13u
        const val gt35: UByte = 14u
        const val gt40: UByte = 15u
        const val gt50: UByte = 16u
        const val gt60: UByte = 17u
        const val gt75: UByte = 18u
        const val gt80: UByte = 19u
        const val gt100: UByte = 20u
        const val lt0: UByte = 21u
        const val lt0p1: UByte = 22u
        const val lt1: UByte = 23u
        const val ltm1: UByte = 24u
        const val ltm2: UByte = 25u
        const val ltm3: UByte = 26u
        const val ltm4: UByte = 27u
        const val ltm5: UByte = 28u
        const val ltm8: UByte = 29u
        const val ltm10: UByte = 30u
        const val ltm15: UByte = 31u
        const val ltm20: UByte = 32u
        const val gt1stdev: UByte = 33u
        const val gt1p5stdev: UByte = 34u
        const val gt2stdev: UByte = 35u
        const val lt1stdev: UByte = 36u
        const val lt1p5stdev: UByte = 37u
        const val lt2stdev: UByte = 38u
    }
}
