// automatically generated by the FlatBuffers compiler, do not modify

package com.openmeteo.sdk;

@SuppressWarnings("unused")
public final class Probability {
  private Probability() { }
  public static final int none = 0;
  public static final int gt0 = 1;
  public static final int gt0p1 = 2;
  public static final int gt1 = 3;
  public static final int gt2 = 4;
  public static final int gt3 = 5;
  public static final int gt4 = 6;
  public static final int gt5 = 7;
  public static final int gt8 = 8;
  public static final int gt10 = 9;
  public static final int gt15 = 10;
  public static final int gt20 = 11;
  public static final int gt25 = 12;
  public static final int gt50 = 13;
  public static final int gt100 = 14;
  public static final int lt0 = 15;
  public static final int lt0p1 = 16;
  public static final int lt1 = 17;
  public static final int ltm1 = 18;
  public static final int ltm2 = 19;
  public static final int ltm3 = 20;
  public static final int ltm4 = 21;
  public static final int ltm5 = 22;
  public static final int ltm8 = 23;
  public static final int ltm10 = 24;
  public static final int gt1stdev = 25;
  public static final int gt1p5stdev = 26;
  public static final int gt2stdev = 27;
  public static final int lt1stdev = 28;
  public static final int lt1p5stdev = 29;
  public static final int lt2stdev = 30;

  public static final String[] names = { "none", "gt0", "gt0p1", "gt1", "gt2", "gt3", "gt4", "gt5", "gt8", "gt10", "gt15", "gt20", "gt25", "gt50", "gt100", "lt0", "lt0p1", "lt1", "ltm1", "ltm2", "ltm3", "ltm4", "ltm5", "ltm8", "ltm10", "gt1stdev", "gt1p5stdev", "gt2stdev", "lt1stdev", "lt1p5stdev", "lt2stdev", };

  public static String name(int e) { return names[e]; }
}

