// automatically generated by the FlatBuffers compiler, do not modify

package com.open_meteo.sdk

@Suppress("unused")
class Aggregation private constructor() {
    companion object {
        const val none: UByte = 0u
        const val minimum: UByte = 1u
        const val maximum: UByte = 2u
        const val mean: UByte = 3u
        const val p10: UByte = 4u
        const val p25: UByte = 5u
        const val median: UByte = 6u
        const val p75: UByte = 7u
        const val p90: UByte = 8u
        const val dominant: UByte = 9u
        const val sum: UByte = 10u
    }
}
