// automatically generated by the FlatBuffers compiler, do not modify

package com.open_meteo.sdk

@Suppress("unused")
class Unit private constructor() {
    companion object {
        const val undefined: UByte = 0u
        const val celsius: UByte = 1u
        const val centimetre: UByte = 2u
        const val cubic_metre_per_cubic_metre: UByte = 3u
        const val cubic_metre_per_second: UByte = 4u
        const val degree_direction: UByte = 5u
        const val dimensionless_integer: UByte = 6u
        const val dimensionless: UByte = 7u
        const val european_air_quality_index: UByte = 8u
        const val fahrenheit: UByte = 9u
        const val feet: UByte = 10u
        const val fraction: UByte = 11u
        const val gdd_celsius: UByte = 12u
        const val geopotential_metre: UByte = 13u
        const val grains_per_cubic_metre: UByte = 14u
        const val gram_per_kilogram: UByte = 15u
        const val hectopascal: UByte = 16u
        const val hours: UByte = 17u
        const val inch: UByte = 18u
        const val iso8601: UByte = 19u
        const val joule_per_kilogram: UByte = 20u
        const val kelvin: UByte = 21u
        const val kilopascal: UByte = 22u
        const val kilogram_per_square_metre: UByte = 23u
        const val kilometres_per_hour: UByte = 24u
        const val knots: UByte = 25u
        const val megajoule_per_square_metre: UByte = 26u
        const val metre_per_second_not_unit_converted: UByte = 27u
        const val metre_per_second: UByte = 28u
        const val metre: UByte = 29u
        const val micrograms_per_cubic_metre: UByte = 30u
        const val miles_per_hour: UByte = 31u
        const val millimetre: UByte = 32u
        const val pascal: UByte = 33u
        const val per_second: UByte = 34u
        const val percentage: UByte = 35u
        const val seconds: UByte = 36u
        const val unix_time: UByte = 37u
        const val us_air_quality_index: UByte = 38u
        const val watt_per_square_metre: UByte = 39u
        const val wmo_code: UByte = 40u
    }
}
